# 2. Scipy

Scipy proviene de Scientific Python

Es una librería de código abierto especializada en resolver problemas de matemática, ciencia e ingeniería, está está construida en base a Numpy y permite la manipulación y visualización de data.

Debido a que es una extensión de Numpy este provee funciones más completas e interactivas que permiten manipular datos desde un nivel alto. Está es una librería muy bien optimizada y es enfocable en múltiples campos como son la programación paralela, web, base de datos, etc. 

Está contiene diferentes subpaquetes que cubren áreas como: Algebra lineal, Constantes matemáticas, Transformadas de Fourier,  Optimización, Estadística, etc.

En este cuaderno se verán múltiples funciones comunes utilizadas en scipy.


Así como hicimos la clase anterior, instalar la librería Scipy si se tiene python y pip instalado, bastaría con instalarlo con el siguiente comando: (``pip install scipy`` )

## Input / Output

Está librería cuenta con un paquete entrada y salida que premite trabajar con diferentes formatos como: Matlab, Arff, Wave, Matrix Market, IDL, NetCDF, TXT.

In [5]:
import numpy as np
from scipy import io as sio

a = np.ones((4,4))


In [6]:
#guardando en un archivo de matlab
sio.savemat('ejemplo.mat', {'a':a})

In [7]:
#listar variables de un archivo en matlab
sio.whosmat('ejemplo.mat')

[('a', (4, 4), 'double')]

In [8]:
#cargar variables de un archivo en matlab
data = sio.loadmat('ejemplo.mat',struct_as_record = True)
data

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Wed Nov 24 19:54:04 2021',
 '__version__': '1.0',
 '__globals__': [],
 'a': array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])}

In [9]:
# se puede acceder a los datos mediante el index como en un diccionario
data['a']

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Scipy Stats

Está librería contiene diferentes funciones de estadística y distribuciones de probabilidad

In [10]:
# distribución normal
from scipy.stats import norm

# cumulative Distribution Function
v = np.array([3,-1,4,-5,10,7,0])
print(norm.cdf(v) )



[9.98650102e-01 1.58655254e-01 9.99968329e-01 2.86651572e-07
 1.00000000e+00 1.00000000e+00 5.00000000e-01]


In [12]:
# Percent Point Function  es la inversa de CDF
print(norm.ppf(0.158))

-1.0027116650265493


In [13]:
print(norm().rvs(3))

[-0.03263487  2.61761007 -0.06205821]


In [16]:
norm.median()

0.0

Ahora podemos ir importando modulos de la libreria de la siguiente manera

In [ ]:
pip install scipy

* Constants: Como Scipy está más enfocado en implementaciones para Ciencia, posee un módulo llamado constants donde se guardan varias constantes que pueden ser utiles al hacer Data Science

In [18]:
  from scipy import constants

Una de ellas es "liter" que devuelve 1 Litro en metros cúbicos.

In [19]:
print(constants.liter)

0.001


In [ ]:
dir(constants)

['Avogadro',
 'Boltzmann',
 'Btu',
 'Btu_IT',
 'Btu_th',
 'ConstantWarning',
 'G',
 'Julian_year',
 'N_A',
 'Planck',
 'R',
 'Rydberg',
 'Stefan_Boltzmann',
 'Wien',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_obsolete_constants',
 'absolute_import',
 'acre',
 'alpha',
 'angstrom',
 'arcmin',
 'arcminute',
 'arcsec',
 'arcsecond',
 'astronomical_unit',
 'atm',
 'atmosphere',
 'atomic_mass',
 'atto',
 'au',
 'bar',
 'barrel',
 'bbl',
 'blob',
 'c',
 'calorie',
 'calorie_IT',
 'calorie_th',
 'carat',
 'centi',
 'codata',
 'constants',
 'convert_temperature',
 'day',
 'deci',
 'degree',
 'degree_Fahrenheit',
 'deka',
 'division',
 'dyn',
 'dyne',
 'e',
 'eV',
 'electron_mass',
 'electron_volt',
 'elementary_charge',
 'epsilon_0',
 'erg',
 'exa',
 'exbi',
 'femto',
 'fermi',
 'find',
 'fine_structure',
 'fluid_ounce',
 'fluid_ounce_US',
 'fluid_ounce_imp',
 'foot',
 'g',
 'gallon',
 'gallon_US

Pueden revisar https://www.w3schools.com/python/scipy/scipy_constants.php para que lo vean de manera ordenada

* Optimize: Nos permite minimizar o maximizar una función expresada donde podemos agregarle cosas como restricciones o qué metodo usar, pero tambien sirve para hallar raices de una ecuación

In [21]:
from scipy import optimize


Si hacemos una comparación con Numpy, como se mencionó en la anterior clase, podemos hallar raices de ecuaciones lineales y de polinomios, pero no podemos hallar raices de ecuaciones no lineales como ``x + cos(x)`` pero si podremos usar: ``optimize.root``

Necesitaremos dos argumentos para usarlo:    
* fun: una función que represente una ecuación
* x0: un punto inicial que pensamos que está cerca de la solución.

In [22]:
import math
def ejemplo(x):
  return math.cos(x) + math.sin(x)

raiz_ejemplo = optimize.root(ejemplo, 0)
print(raiz_ejemplo) #nos genera todo un objeto que contiene todo esto:

    fjac: array([[-1.]])
     fun: 0.0
 message: 'The solution converged.'
    nfev: 7
     qtf: array([-7.96885813e-09])
       r: array([-1.41421356])
  status: 1
 success: True
       x: array([-0.78539816])


In [23]:
raiz_ejemplo.x #nos dará el punto solución

array([-0.78539816])

In [ ]:
#1.1102230246251565e-16  
# abs(float1 - float2) < eps

ejemplo(raiz_ejemplo.x)  # cero

1.1102230246251565e-16

Tambien pudimos haber llamado a la función root de esta manera, si es que la vamos a usar seguidamente

In [ ]:
from scipy.optimize import root

In [ ]:
root(ejemplo, 0).x

array([-0.78539816])

Usaremos ``minimize`` para minimizar una función, esta tomará más argumentos que root:    
* fun: es la función como una ecuación
* x0: es el punto inicial que pensamos está cerca a la solución
* method: Debemos de elegir que método de minimización usaremos: 
  -   ``'CG'``          # Gradiente conjugado
  -``'BFGS'``       #Broyden–Fletcher–Goldfarb–Shanno
  -   ``'Newton-CG'`` 
  -  ``'L-BFGS-B'``
  - ``'TNC'``    #Newton Truncado
  - ``'COBYLA'`` #optimización restringida por aproximación lineal
  - ``'SLSQP'`` # usar minimos cuadrados de manera secuencial

* Options: Es un diccionario que contiene caracteristicas que queremos que cumpla la solución, por ejemplo:     
  - "maxiter" : ``int``, numero de iteraciones maximas que queremos que se ejecuten
  - "disp": ``bool``,    si es ``True`` se imprimen detalles de la convergencia
  - "gtol":  ``float``, es la tolerancia del error

In [24]:
from scipy.optimize import minimize
def prueba(x):
  return math.sin(x) + math.cos(x)

min_prueba = minimize(prueba, 0, method = 'BFGS')
print(min_prueba)

      fun: -1.4142135623730887
 hess_inv: array([[0.70721448]])
      jac: array([1.49011612e-07])
  message: 'Optimization terminated successfully.'
     nfev: 16
      nit: 4
     njev: 8
   status: 0
  success: True
        x: array([-2.3561944])


In [25]:
import numpy as np
# función que quieres obtener el mínimo
def prueba(x):
  return (x[0]-5)**2 + (7-x[1])**2
(x-5)^2 + (7-y)^2

# punto inicial
x0 = np.array([1,1])

# Uilizas método minimize
min_prueba = minimize(prueba, x0, method = 'BFGS')
print(min_prueba)

      fun: 5.38420786206946e-12
 hess_inv: array([[ 0.84615405, -0.23076913],
       [-0.23076913,  0.65384599]])
      jac: array([ 4.12628118e-06, -2.13762894e-06])
  message: 'Optimization terminated successfully.'
     nfev: 12
      nit: 3
     njev: 4
   status: 0
  success: True
        x: array([5.00000206, 6.99999892])


In [26]:
def prueba(x):
    return (x[0]-5)**2 + (7-x[1])**2
    # (x-5)^2 + (7-y)^2
                                        # x - y + 5 >= 0
restricciones = ({'type': 'ineq', 'fun': lambda x: x[0] - x[1] + 5}, #Desigualdad >= 0
                                     # 2*x - y + 1 >= 0
        {'type': 'ineq', 'fun': lambda x: 2*x[0] - x[1] + 1}) #Desigualdad >= 0
# x >= 0
# y >= 0
cotas = ((0,None),(0,None))


resultado = minimize(prueba, (1,1), method = 'SLSQP', bounds = cotas, constraints = restricciones)
print(resultado)

     fun: 0.0
     jac: array([1.49011612e-08, 1.49011612e-08])
 message: 'Optimization terminated successfully'
    nfev: 7
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([5., 7.])


In [27]:
def prueba(x):
    return (x[0]-5)**2 + (7-x[1])**2

restricciones = ({'type': 'ineq', 'fun': lambda x: x[0] - x[1] + 5}, 
        {'type': 'ineq', 'fun': lambda x: 2*x[0] - x[1]- 4}) #Ahora la solucion obvia no cumple esta restricción
cotas = ((0,None),(0,None))
resultado = minimize(prueba, (1,1), method = 'SLSQP', bounds = cotas, constraints = restricciones)
print(resultado)

     fun: 0.2000000115541445
     jac: array([ 0.80009616, -0.3998077 ])
 message: 'Optimization terminated successfully'
    nfev: 14
     nit: 4
    njev: 4
  status: 0
 success: True
       x: array([5.40004807, 6.80009614])
