# 1. Introducción y objetivos 

Ahora, despues de obtener buenos fundamentos de introducción al Python, podemos empezar a ver la superficie de una de las librerias más conocidas de Python, Numpy

Primero, veremos porqué numpy es tan importante y que nos ofrece (ndarray).

Luego, veremos como estos se pueden trabajar de distintas maneras y como podemos jugar con ellos

Trataremos de cubrir todo lo que podamos pues es un tema extenso

Al finalizar este tema habremos conseguido los siguientes objetivos: 

* Conocer como crear ndarrays de numpy.
* Aprender a trabajarlos a nuestra manera como nos sea más comodos
* Poder operar entre estos objetos. 

# 2. Numpy

Numpy proviene de "Numerical Python", es una libreria de Python que se usa para trabajar con arrays, estos son muy usados en Ciencia de Datos. 

Numpy crea un objeto array llamado ndarray que puede ser hasta 50 veces más rápido que las listas en python y dado que incluye muchas funciones que hacen que trabajar con estos nuevos objetos sea mucho más facil.


Dado que jupyter notebook viene instalado numpy por defecto, solo tendremos que importarlo en el cuaderno de trabajo para poder usarlo (Si en otro ambiente poseen python y pip instalado, bastaría con instalar numpy con el siguiente comando: ``pip install numpy`` )

In [1]:
import numpy

Ahora ya tenemos numpy importado y por lo tanto podemos usarlo inmediatamente. A continuación, veremos como funciona numpy:

In [5]:
lista = [2,3,5,7,11,13]
listan = numpy.array(lista)
print(lista)
print(listan)

[2, 3, 5, 7, 11, 13]
[ 2  3  5  7 11 13]


Para hacer más comodo trabajar con numpy, pues usaremos varias funciones, es muy común darle el alias de ``np``, así: 

In [3]:
import numpy as np

Ahora podremos usar ``numpy`` como ``np`` 

In [12]:
lista1 = [2,3,5,7,11,13]
lista1n = np.array(lista1)
print(lista1)
print(lista1n)

[2, 3, 5, 7, 11, 13]
[ 2  3  5  7 11 13]


Ahora veamos paso por paso como podemos crear arrays y trabajar con ellos
en ``numpy``: 

* ``array()``: Esta función nos permite generar un ndarray para trabajar en numpy a partir de cualquier objeto array como una lista, tuplas, etc:

En una lista:

In [32]:
lista = [2,3,5,7,11,13]
print(type(lista))
lista = np.array(lista)
print(type(lista))
print(lista)

<class 'list'>
<class 'numpy.ndarray'>
[ 2  3  5  7 11 13]


En una tupla:

In [33]:
lista = (2,3,5,7,11,13)
print(type(lista))
lista = np.array(lista)
print(type(lista))
print(lista)

<class 'tuple'>
<class 'numpy.ndarray'>
[ 2  3  5  7 11 13]


Usarlo en conjuntos genera problemas:

In [5]:
lista = {2,3,5,7,11,13}
lista = np.array(lista)
print(type(lista))
print(lista)

<class 'numpy.ndarray'>
{2, 3, 5, 7, 11, 13}


Usarlo en strings no funciona como se podría pensar:

In [43]:
for i in "runrun":
    print(i)

r
u
n
r
u
n


In [42]:
lista = "RunRun"
print(type(lista))
lista = numpy.array(lista)
print(type(lista))
print(lista)

<class 'str'>
<class 'numpy.ndarray'>
RunRun


Índices (*Indexing*): con ellos podemos obtener elementos de los arrays, recordar que en numpy al igual que en Python los índices empiezan en 0

In [50]:
lista = np.array([2,3,5,7,11,13])
print(lista[0])
print(lista[5])
print(lista[-1])

2
13
13


Ahora, crearemos estos arrays pero para más dimensiones.

Veamos para una 2-Dimensional (podremos pensar en estos como una tabla con filas y columnas, como si fuera una matriz):

In [53]:
matri = np.array([[1,3,5,7,9], [2,4,6,8,10]])
print(matri)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


Los indices ahora serán 2, mostremos el valor de la fila 2 y columna 4

In [55]:
matri[1,3]

8

Para un array 3-Dimensional, pues la idea es natural: ahora necesitaremos especificar 3 valores:

In [56]:
var = np.array([[[1,3,5,7,9], [2,4,6,8,10]],[[2,3,5,7,11],[13,17,19,23,29]]])

In [61]:
print(var)

[[[ 1  3  5  7  9]
  [ 2  4  6  8 10]]

 [[ 2  3  5  7 11]
  [13 17 19 23 29]]]


In [57]:
var[0,0,0]

1

In [59]:
var[1,1,4]

29

In [60]:
var[0,1,3]

8

Explicación:
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>

* Rebanadas (*Slicing*): Con estos podemos tomar conjuntos de elementos desde un índice hasta otro en cualquier array.
Podemos pasarlo de este tipo:
``[inicio:fin]``
De esta manera tomamos todos los elementos desde el inicio hasta el fin sin considerarlo

``[inicio:fin:salto(paso)]`` De esta manera especificamos los pasos:

* Si no especificamos el inicio, entonces empieza desde 0

* si no especificamos el fin, entonces nos dá todos los indices desde el inicio especificado

* si no especificamos el paso, entonces lo considera como 1

In [9]:
lista = np.array([2,3,5,7,11,13])
lista[1:4]

array([3, 5, 7])

In [7]:
# for i in range(1,4):
#   print(i)

In [13]:
lista[-4:]

array([ 5,  7, 11, 13])

In [84]:
lista[:]

array([ 2,  3,  5,  7, 11, 13])

In [14]:
var = np.array([[[1,3,5,7,9], [2,4,6,8,10]],[[2,3,5,7,11],[13,17,19,23,29]]])
var[0, : , : ]

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

Tipos de Datos en Numpy:
* ``i`` - integer
* ``b`` - boolean
* ``u`` - unsigned integer
* ``f`` - float
* ``c`` - complex float
* ``O`` - object
* ``S`` - string
* ``m`` - timedelta
* ``M`` - datetime
* ``U`` - unicode string
* ``V`` - fixed chunk of memory for other type ( void )

In [86]:
lista = np.array([2,3,5,7,11,13])
lista.dtype

dtype('int32')

In [16]:
ejem = np.array(["Hola","quetal","es","un","ejempl"])
ejem.dtype

dtype('<U6')

In [20]:
ejem = np.array(["Hola","quetal","es","un","ejempl", 5.5])
ejem.dtype

dtype('<U32')

* Copy vs View: 
Hay dos métodos con los que podemos trabajar dado un array fijo. 

* Copy: creamos una copia exacta del array con el cual podemos manejar y no afectará al array original y viceversa, se dice que posee la data
* View: vemos el array, los cambios en el view afectarán al array original y viceversa, no posee la data.


In [26]:
lista = np.array([2,3,5,7,11,13])
x = lista.copy()

In [27]:
x

array([ 2,  3,  5,  7, 11, 13])

In [28]:
x[1] = 1
x

array([ 2,  1,  5,  7, 11, 13])

In [25]:
lista

array([ 2,  3,  5,  7, 11, 13])

In [39]:
lista = np.array([2,3,5,7,11,13])
x = lista.view()

In [40]:
x

array([ 2,  3,  5,  7, 11, 13])

In [41]:
x[0] = 15
x

array([15,  3,  5,  7, 11, 13])

In [42]:
lista

array([15,  3,  5,  7, 11, 13])

In [44]:
x = lista.view()
x

array([15,  3,  5,  7, 11, 13])

Podemos ver que son si usamos ``.base``, si sale ``None``, entonces es un array que posee los datos. Sino, nos devolverá de done provinene los datos

In [45]:
lista = np.array([2,3,5,7,11,13])
x = lista.view()
y = lista.copy()
print(x.base)
print(y.base)

[ 2  3  5  7 11 13]
None


* ``.ndim`` :  Nos indica las dimensiones del ndarray

In [46]:
lista = np.array([2,3,5,7,11,13])
lista.ndim

1

In [48]:
otro = np.array([1,2,3])
otro.ndim

1

In [47]:
var = np.array([[[1,3,5,7,9], [2,4,6,8,10]],[[2,3,5,7,11],[13,17,19,23,29]]])
var.ndim

3

* ``.shape`` : si la usamos en un array, nos devolverá una tupla con la cantidad de elementos en cada dimensión

In [149]:
lista = np.array([2,3,5,7,11,13])
lista.shape

(6,)

In [49]:
matri = np.array([    [1,3,5,7,9], [2,4,6,8,10]     ])
matri.shape

(2, 5)

In [154]:
var = np.array([[[1,3,5,7,9], [2,4,6,8,10]],[[2,3,5,7,11],[13,17,19,23,29]] ])
var.shape

(2, 2, 5)

* ``.reshape`` : si la usamos en un array, podemos cambiar la forma (shape) de este, podemos agregar o reducir las dimensiones
    o cambiar la cantidad de elementos por dimensión

In [157]:
lista = np.array([2,3,5,7,11,13])
lista.reshape(3,2)

array([[ 2,  3],
       [ 5,  7],
       [11, 13]])

In [158]:
lista = np.array([2,3,5,7,11,13])
lista.reshape(2,3)

array([[ 2,  3,  5],
       [ 7, 11, 13]])

In [50]:
lista = np.array([2,3,5,7,11,13,15,17])
lista.reshape(2,2,2)

array([[[ 2,  3],
        [ 5,  7]],

       [[11, 13],
        [15, 17]]])

Podremos cambiar a cualquier forma siempre y cuando se mantegan la cantidad de elementos

Dado que se cumple esa propiedad, podemos no especificar un valor para una dimensión y aún asi funcionará (lo llenamos con -1 y Numpy hará el resto)

In [171]:
lista = np.array([2,3,5,7,11,13,17,19])
x = lista.reshape(2,2,-1)
print(x)

[[[ 2  3]
  [ 5  7]]

 [[11 13]
  [17 19]]]


Podemos convertir un array cualquiera a 1-dimensional de esta forma:

In [172]:
x.reshape(-1)

array([ 2,  3,  5,  7, 11, 13, 17, 19])

Como veremos a continuación, el resultado es un tipo view

In [173]:
lista = np.array([2,3,5,7,11,13,17,19])
x = lista.reshape(2,2,2)
print(x.base) 

[ 2  3  5  7 11 13 17 19]


* Iteración: podemos iterar en estos arrays y el resultado dependerá de la cantidad de For s que usemos

In [174]:
matri = np.array([[1,3,5,7,9], [2,4,6,8,10]])
for i in matri:
    print(i)

[1 3 5 7 9]
[ 2  4  6  8 10]


In [175]:
matri = np.array([[1,3,5,7,9], [2,4,6,8,10]])
for i in matri:
    for j in i:
        print(j)

1
3
5
7
9
2
4
6
8
10


* Podemos Juntar varios arrays usando la función ``np.concatenate`` junto que dimensión vamos a considerar para unirlos, si no se especifica usará 0 por defecto:

In [190]:
l = np.array([1,3,5,7,9])
v = np.array([2,4,6,8,10])
arr = np.concatenate((l,v),0)
print(arr)

[ 1  3  5  7  9  2  4  6  8 10]


In [55]:
m1= np.array([[1,3,5,7,9], [2,4,6,8,10]])

m2= np.array([[11,13,15,17,19], [12,14,16,18,20]])

arr = np.concatenate((m1, m2), axis=1)

print(arr)

[[ 1  3  5  7  9 11 13 15 17 19]
 [ 2  4  6  8 10 12 14 16 18 20]]


* Si por otro lado queremos unirlos pero agregando otra dimensión, usaremos ``np.stack``

In [57]:
l = np.array([1,3,5,7,9])
v = np.array([2,4,6,8,10])
arr = np.stack((l,v),1)
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


* Podemos separar el array en varios usando ``np.array_split()``, el resultado será un array que contenga los arrays separados, si la cantidad de elementos no da para hacer una buena repartición, el ultimo array se adaptará

In [209]:
lista = np.array([2,3,5,7,11,13,17,19])
listap = np.array_split(lista,3)
print(listap)

[array([2, 3, 5]), array([ 7, 11, 13]), array([17, 19])]


In [59]:
m1= np.array([[1,3,5,7,9], [2,4,6,8,10]])
arr = np.array_split(m1,2)
print(arr)

[array([[1, 3, 5, 7, 9]]), array([[ 2,  4,  6,  8, 10]])]


In [219]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [220]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


Se puede especificar bajo que eje queremos realizar el split

In [61]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis = 1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


``np.where()``

In [70]:
lista = np.array([1,2,8,23,44,545,16,71,8,9,10])

x = np.where(lista%2== 0)
x

(array([ 1,  2,  4,  6,  8, 10], dtype=int64),)

``np.sort()``

In [74]:
np.sort(lista)

array([  1,   2,   8,   8,   9,  10,  16,  23,  44,  71, 545])

In [77]:
A = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 2]])

In [78]:
np.linalg.inv(A)

array([[1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 0.5]])

In [79]:
np.sin(A)

array([[0.84147098, 0.        , 0.        ],
       [0.        , 0.84147098, 0.        ],
       [0.        , 0.        , 0.90929743]])